name: check-for-emails
on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]
jobs:
  find_emails:
    runs-on: ubuntu-latest
    name: Check for emails in issue comments
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Scan comment
      id: scan
      uses: FlowCrypt/comment-email-address-alerts@v21
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exemptions: test,example.com,flowcrypt.com
        ignoredEmails: flowcrypt.compatibility@gmail.com
